name: Docker Image CI
on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login in quay
      run: docker login quay.io -u ${QUAY_USER} -p ${QUAY_TOKEN}
      env:
        QUAY_USER: ${{ secrets.QUAY_USERNAME }}
        QUAY_TOKEN: ${{ secrets.QUAY_PASSWORD }}
    - name: Check out code
      uses: actions/checkout@master
    - name: Build the Docker images
      run: docker build --no-cache -t quay.io/krkn-chaos/cerberus containers/
    - name: Push the Docker images
      run: docker push quay.io/krkn-chaos/cerberus
    - name: Remove Image
      run: docker rmi -f quay.io/krkn-chaos/cerberus | exit 0
    - name: Rebuild krkn-hub
      if: startsWith(github.ref, 'refs/tags')
      uses: redhat-chaos/actions/krkn-hub@main
      with:
        QUAY_USER: ${{ secrets.QUAY_USERNAME }}
        QUAY_TOKEN: ${{ secrets.QUAY_PASSWORD }}
        AUTOPUSH: ${{ secrets.AUTOPUSH }}
